name: Deploy to Slot

on:
  push:
    branches:
      - appServiceSlot_Working_DO_NOT_MERGE
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: |
          cd appServiceSlot
          dotnet build SlotDemo.sln --configuration Release

      - name: dotnet publish
        run: |
          cd appServiceSlot
          dotnet publish SlotDemo.sln -c Release -o ../publish

      - name: Deploy to Azure Web App Slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myapp-app'
          slot-name: 'myapp-slot'
          publish-profile: ${{ secrets.AZURE_WEBAPP_SLOT_PUBLISH_PROFILE }}
          package: ./publish